'use strict';

const Joi = require('joi');

module.exports = Joi.object().keys({
  timestamp: Joi.number(),
  dateTime: Joi.string().required(),
  date: Joi.string().required(),
  id: Joi.string().regex(/^[0-9]+$/).required(),
  projectId: Joi.number().integer().required(),
  name: Joi.string().required(),
  uid: Joi.string().regex(/^[0-9]+$/),
  ip: Joi.string().allow(''),
  userAgent: Joi.string().allow(''),
  page_url: Joi.string(),
  page_referrer: Joi.string().allow(''),
  page_title: Joi.string().allow(''),
  session_type: Joi.string().allow(''),
  session_engine: Joi.string().allow(''),
  session_num: Joi.number(),
  session_pageNum: Joi.number().integer(),
  session_eventNum: Joi.number().integer(),
  session_hasMarks: Joi.boolean(),
  session_marks_key: Joi.array().items(Joi.string()),
  session_marks_value: Joi.array().items(Joi.string().allow('')),
  session_start: Joi.number(),
  session_refHost: Joi.string().allow(''),
  lib_name: Joi.string().allow(''),
  lib_libver: Joi.number(),
  lib_snippet: Joi.number(),
  client_type: Joi.string().allow(''),
  client_name: Joi.string().allow(''),
  client_version: Joi.string().allow(''),
  client_tz: Joi.string().allow(''),
  client_ts: Joi.number(),
  client_tzOffset: Joi.number(),
  client_platform: Joi.string().allow(''),
  client_product: Joi.string().allow(''),
  browser_if: Joi.array().items(Joi.number()),
  browser_wh_w: Joi.number(),
  browser_wh_h: Joi.number(),
  browser_sr_tot_w: Joi.number(),
  browser_sr_tot_h: Joi.number(),
  browser_sr_avail_w: Joi.number(),
  browser_sr_avail_h: Joi.number(),
  browser_sr_asp: Joi.number(),
  browser_sr_oAngle: Joi.number(),
  browser_sr_oType: Joi.string().allow(''),
  country_iso: Joi.string().allow(''),
  country_name_ru: Joi.string().allow(''),
  country_name_en: Joi.string().allow(''),
  region_iso: Joi.string().allow(''),
  region_name_ru: Joi.string().allow(''),
  region_name_en: Joi.string().allow(''),
  city_id: Joi.number().allow(''),
  city_name_ru: Joi.string().allow(''),
  city_name_en: Joi.string().allow(''),
  os_name: Joi.string().allow(''),
  os_version: Joi.string().allow(''),
  os_platform: Joi.string().allow(''),
  device_type: Joi.string().allow(''),
  device_brand: Joi.string().allow(''),
  device_model: Joi.string().allow(''),
  campaign: Joi.string().allow(''),
  source: Joi.string().allow(''),
  isBot: Joi.number().integer(),
  data_key: Joi.array().items(Joi.string()),
  data_value: Joi.array().items(Joi.string().allow('')),
  user_id: Joi.string().allow(''),
  user_traits_key: Joi.array().items(Joi.string()),
  user_traits_value: Joi.array().items(Joi.string().allow('')),
  user_gaId: Joi.string().allow(''),
  user_ymId: Joi.string().allow(''),
});


// page_number утсревшее поле, испольузется как дефолт к session_pageNum
